name: build
on:
  push:
    tags:
      - 'v*'

env:
  JAVA_VERSION: 17

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 5
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: ${{env.JAVA_VERSION}}
          server-id: github
          cache: gradle
      - name: Build
        run: ./gradlew build
      - name: Get version
        id: get-version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "publishing version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Publish
        run: ./gradlew publish -Pversion=${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
